name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - run: npm ci
      - name: cypress-test
        uses: cypress-io/github-action@v4
        with:
          command: npm run cy:run
          command-prefix: "--"
          start: npm run start-prod
          wait-on: http://localhost:5000


